### ISSUE TITLE
❓👂 Question/Feedback - KQL files under "general-networking" and "network-watcher" have the same ID

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library#160]
## Question/Feedback

KQL files under the `general-networking` and `network-watcher` have the same ID. Is this expected?

- `nw-1` in `general-networking`
    - https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/main/docs/content/services/networking/general-networking/code/nw-1/nw-1.kql

- `nw-1` in `network-watcher`
    - https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/main/docs/content/services/networking/network-watcher/code/nw-1/nw-1.kql

## Possible Answers/Solutions?

I'm guessing each query file has a unique ID for easy identification.

**Comment by oZakari** [comment]
Hi @tksh164, thanks for calling this out! The service acronyms are aligned with the [CAF documentation](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations). 

Since General Networking is not specific to an individual Azure Service it looks like a generalized acronym was used as well. Having the same acronym shouldn't cause any issues with the tooling, but it may cause confusion for customers so I think it makes sense to transition the General Networking acronym to `gnw` which doesn't appear to be used for any other services.

No worries if not, but would you be interested in creating a PR for this?

**Comment by tksh164** [comment]
@oZakari Thank you for your comments. Sure, I will create PR for this.
